pipeline {
    agent {
        label 'cms-dmwm-el9-10'
    }

    environment {
        MY_HOSTNAME = """${sh(
            returnStdout: true,
            script: 'hostname -f'
        ).trim()}"""

        MY_ID = """${sh(
            returnStdout: true,
            script: 'id -u'
        ).trim()}"""

        MY_GROUP = """${sh(
            returnStdout: true,
            script: 'id -g'
        ).trim()}"""

        HOST_MOUNT_DIR = "${env.WORKSPACE}"
        
        WMA_TAG = '2.3.3'
        COUCH_TAG = '3.2.2'
        MDB_TAG = '10.6.5'

        ghprbPullId = '11995'
        ghprbTargetBranch = 'master'

    }

    stages {
        stage('Setup') {
            steps {
                git branch: 'main', url: 'https://github.com/d-ylee/jenkins-test'
                sh '''
                   echo "Setting up workspace directories"
                   $WORKSPACE/WMCore-Test-Base/setup-env.sh
                   ls $WORKSPACE
                   echo "python3 version"
                   python3 --version
                   '''
            }
        }
        stage('Run pylint tests') {
            steps {
                sh ''' 
                   docker compose -f $WORKSPACE/WMCore-Test-Base/docker-compose.yml up --quiet-pull -d wmcore-pr-pylint
                   docker compose -f $WORKSPACE/WMCore-Test-Base/docker-compose.yml exec wmcore-pr-test /home/cmsbld/ContainerScripts/pylintTest.sh
                   '''
            }
        }
    }

    post {
        always {
            sh 'docker compose -f $WORKSPACE/WMCore-Test-Base/docker-compose.yml down'
        }
    }
}
