pipeline {
    agent {
        label 'cms-dmwm-el9-01'
    }

    environment {
        MY_HOSTNAME = """${sh(
            returnStdout: true,
            script: 'hostname -f'
        ).trim()}"""

        MY_ID = """${sh(
            returnStdout: true,
            script: 'id -u'
        ).trim()}"""

        MY_GROUP = """${sh(
            returnStdout: true,
            script: 'id -g'
        ).trim()}"""

        HOST_MOUNT_DIR = "${env.WORKSPACE}"
        
        WMA_TAG = '2.3.3'
        COUCH_TAG = '3.2.2'
        MDB_TAG = '10.6.5'

    }

    stages {
        stage('Test compose') {
            steps {
                git branch: 'main', url: 'https://github.com/d-ylee/jenkins-test'
                sh ''' 
                   mkdir -p $WORKSPACE/admin/wmagent $WORKSPACE/admin/mariadb $WORKSPACE/certs
                   cp /home/cmsbld/.globus/dmwm-config.tmpl $WORKSPACE/admin/wmagent/WMAgent.secrets
                   cp /home/cmsbld/.globus/dmwm-mariadb.tmpl $WORKSPACE/admin/mariadb/MariaDB.secrets
                   cp /home/cmsbld/.globus/*.pem $WORKSPACE/certs
                   sed -i 's/6994/5984/g' $WORKSPACE/admin/wmagent/WMAgent.secrets
                   sed -i 's/COUCH_HOST=0\.0\.0\.0/COUCH_HOST=couchdb/g' $WORKSPACE/admin/wmagent/WMAgent.secrets
                   docker compose -f $WORKSPACE/WMCore-PR-test/docker-compose.yml up -d wmagent-dev
                   docker compose -f $WORKSPACE/WMCore-PR-test/docker-compose.yml exec wmagent-dev "/home/dmwm/TestScripts/pylintWMCore.sh"
                   '''
            }
        }
    }

    post {
        always {
            sh 'docker compose -f $WORKSPACE/WMCore-PR-test/docker-compose.yml down'
        }
    }
}
