pipeline {
    agent {
        label 'cms-dmwm-el9-01'
    }

    environment {
        MY_HOSTNAME = """${sh(
            returnStdout: true,
            script: 'hostname -f'
        ).trim()}"""

        MY_ID = """${sh(
            returnStdout: true,
            script: 'id -u'
        ).trim()}"""

        MY_GROUP = """${sh(
            returnStdout: true,
            script: 'id -g'
        ).trim()}"""

        HOST_MOUNT_DIR = "${env.WORKSPACE}"
        
        WMA_TAG = '2.3.3'
        COUCH_TAG = '3.2.2'
        MDB_TAG = '10.6.5'

    }

    stages {
        stage('Test compose') {
            steps {
                git branch: 'main', url: 'https://github.com/d-ylee/jenkins-test'
                sh 'docker compose -f $WORKSPACE/WMCore-PR-test/docker-compose.yml up -d wmagent-unittest'
                sh 'docker compose -f $WORKSPACE/WMCore-PR-test/docker-compose.yml exec wmagent-unittest "/home/dmwm/TestScripts/pylintWMCore.sh"'
            }
        }
    }

    post {
        always {
            sh 'docker compose -f $WORKSPACE/WMCore-PR-test/docker-compose.yml down'
        }
    }
}
