pipeline {
    agent {
        label 'cms-dmwm-el9'
    }

    environment {
        CODE_REPO = "WMCore"
        WMCORE_REP = "dmwm"
    }

    stages {
        stage('Setup') {
            steps {
                copyArtifacts filter: 'artifacts/nosetest*.xml', fingerprintArtifacts: true, projectName: 'WMCore-Unittest-Baseline', selector: lastWithArtifacts(), target: 'artifacts'

                sh '''
                echo "$(TZ=GMT date): Job name is $JOB_NAME"

                echo "Creating a venv at $WORKSPACE and install dependencies"
                python3 -m venv .
                source $WORKSPACE/bin/activate
                $WORKSPACE/bin/pip install PyGithub xunitparser

                '''
            }
        }
        stage('Compare tests') {
            steps {
                sh '''
                ls $WORKSPACE

                git clone https://github.com/dmwm/WMCore.git code

                echo "$(TZ=GMT date): comparing tests..."

                $WORKSPACE/bin/python ./ContainerScripts/CompareTests.py nosetestspy3

                pushd code
                `git tag |grep JENKINS| sort | tail -1 > LatestTag`
                popd
                '''
            }
        }
    }
}